### PR TITLE
Optimization pass on LBA slim from 2.3

### PR DESCRIPTION
**Pull request by ThunderRahja**
I hate Dread Hudson.

This updates LBA-slim to remove its anti-grief features and return it to its original objective of being lightweight and "slim." It also changes `rev` from a float to a string to remove an unnecessary function call in all editions. LBA 2.22 is obsolete at this point and has been removed.

For some reason, using the Github website to edit LBA-slim marked it as deleted and added, so diff will have to be checked manually. I'm not doing this a third time.

### CODE REVIEW

**Comment by HadetTheUndying** [comment]
Will test for 7 days then merge if no new bugs are introduced

**Comment by SinStraaf** [comment]
Update seems good from a code perspective, probably a fair bit of redundant
and overlooked code from previous versions.
Storing the version as a float was probably a mistake or may have been a
memory saving tactic, either way no performance would be lost to change.

**Comment by ThunderRahja** [comment]
> Will test for 7 days then merge if no new bugs are introduced

How's it looking?

**Comment by HadetTheUndying** [comment]
Looks fine to me. @Krutchen please take a look when you have a chance. Will merge over the weekend otherwise

**Comment by Krutchen** [comment]
Looks fine, I'm just wary about changing revision from a float to string if it'd break something like automated version checking from people putting stuff that doesn't convert back to a float well in there. Right now the current way of denoting the different types is LBA.v.(L/D),####, if people decided to move the denotation into the rev string it could break stuff like weapons that only deliver damage to LBA Light things. I'm also not entirely sure about removing the bare minimum baby anti grief because it frustrates smoothbrain attempts at griefing, but just capping repairs to -maxhp should work well enough.

**Comment by ThunderRahja** [comment]
If people put in non-standard revision numbers then that’s on them for breaking automatic parsing. The description string looks like “LBA.v.L.2.31,100,200” for an LBA light version 2.31 with 100 HP and 200 max HP. The revision number was being cast as a string anyway, so this cuts out an unnecessary extra step, and people shouldn’t be changing the revision number anyway.

The whole point of slim is to make it as lightweight as possible. If creators want anti-grief in their gear they can still use LBA light-deployable.

**Pull request merged**
