### PR TITLE
LBA v.2.3

### PR DESCRIPTION
**Pull request by Krutchen**
Preliminary upload for LBA v.2.3
THIS IS A HIGHLY EXPERIMENTAL VERSION. DO NOT DEPLOY THIS IN YOUR EQUIPMENT UNTIL IT IS PROPERLY TESTED AND VETTED.
BIG NEW CHANGES TO ANTI-GRIEF FUNCTIONALITY!

Changelog
//2.22 -> 2.3
//+Removed Blackbox support, very ancient code, will be redone sometime in the future.
//+Reworked anti-grief, recent list no longer flat out rejects damage for things found, instead used in anti-grief
//  Anti-Grief will now collect data over several seconds instead of just in that specific event
//  Rezzer Key chaining will now be used to get the rezzer or vehicle size, affecting max DPS allowed. 
//  Rezzers that have a complete LBA description of (LBA.v.,hp,maxhp) and more than 1 script will be considered to be a valid rezzer
//  Recents list will now be cleaned per entry by first time damage was applied. recent+=[owner,osrc,dmg,atcap,llGetTime()] & total+=[owner,damage], default time for cleaning recent is 4s
//  AT Cap is now generated by hitbox size of a valid rezzer, otherwise there's a flat 75 based on source
//  Blacklisting now triggers on 1.25 of cap, otherwise damage is silently dropped in case of things that are SLIGHTLY borderline.
//  Totals list will track an avatars TOTAL DAMAGE over the lifetime of the vehicle. If someone gets blacklisted by exceeding DPM their entry in total will be refunded.
//  For the sake of the antigrief functioning, PROC has to be cleared before it can die. But other than that, damage is now processed when you recieve it and not with a 1s proc delay.
//  Also has lazy namespace dropping, if it's just a key or a float/integer it gets dropped because that's baby grief
//  if((key)n)return;
//  if ((string)((float)n)==n||(string)((integer)n)==n)return;

### CODE REVIEW

**Comment by Krutchen** [comment]
Few things. Looks like I forgot to do a Owner & Obj Name comparison in the new blacklisting functionality, so AT nodes aren't getting caught and clumped together. This is allowing for this kind of stuff :

Hit by Sari (criss.ixtar)  with '[Nuke Node.LBA]: - 75 DMG' 5 times for 375 damage 
Hit by Sari (criss.ixtar)  with '[Nuke Node.LBA]: - 25 DMG' for 25 damage

This will be fixed tonight.

"Dread HudsonToday at 8:23 AM
I think i forgot to make same name override the inherit the sourcing mechanic so AT nodes are fucking around
Just need to do a check for name, then compare owner, and then just add to that instead of giving that key a new recents entry"

fixxed 8/16/2020

[18:04] Object: dif source same name same owner
[18:04] Object :: David Hudson (dread.hudson) has exceeded their AT Cap for [Nuke Node.LBA]: - 75 DMG of 75 with 150 total damage! 
        This avatar has sourced 150 before being blacklisted. Blacklisting and refunding all damage!
[18:04] Object: 
Hit by David Hudson (dread.hudson) with '[Nuke Node.LBA]: - 75 DMG' for 75 damage

**Comment by Krutchen** [comment]
Also AT mines and Satchels are going to be a problem as they were with LBA 2.2 and below.
Secondary suggested use just do a time flag in the description until LL finally gets around to putting in OBJECT_REZ_TIME

Malefactor-IXToday at 8:19 AM
Maybe we can create a workaround for mines that has them store their time of rezzing in the description?
Dread HudsonToday at 8:20 AM
Idk
Malefactor-IXToday at 8:20 AM
ie. llSubStringIndex(description,"mine:")
And then the time listed is llGetTimeOfDay so it syncs across multiple scripts

This would be a pretty simple fix without needing much rescripting for everyone, just a quick update, my main concern is what if some assholes start putting that in their munitions? We'd need to have a few other things to verify its a mine.

**Comment by HadetTheUndying** [comment]
You could have done this in your previous PR it didn't need to be closed, Other than that let's try the mine thing and see if it works, that requires a big update pass on the part of everyone in the community though.

**Comment by Krutchen** [comment]
Update LBA-v2.3.lsl

Fixxed 'different source same name' shit Criss reported earlier, this should fix AT emitters being able to get around the antigrief because they're using different prims for each damage.
implemented Secondary's suggestion of using a "time flag" in mine desc, use "llSetObjectDesc("LBA.v.,t:"+(string)llGetTimeOfDay());" in your landmine's desc.
Also checks if the "mine" is under 1mx1mx1m.

**Review by ThunderRahja — CHANGES_REQUESTED** [review]
This feels like two steps forward, two steps back. `atcap` is defined in multiple locations with two different numerals and modified in several more locations. The previous version allowed `atcap` to be defined and customized above the "don't edit below this" line in one easy to understand variable. This file should be named `LBA-v2.23.lsl` and not `LBA-v2.3.lsl`, which is ironic considering v2.22's relative ease of use. Rather than enable or disable anti-grief via a variable, I suggest removing the anti-grief components altogether as a separate, lightweight script.

**Comment by HadetTheUndying** [comment]
> This feels like two steps forward, two steps back. `atcap` is defined in multiple locations with two different numerals and modified in several more locations. The previous version allowed `atcap` to be defined and customized above the "don't edit below this" line in one easy to understand variable. This file should be named `LBA-v2.23.lsl` and not `LBA-v2.3.lsl`, which is ironic considering v2.22's relative ease of use. Rather than enable or disable anti-grief via a variable, I suggest removing the anti-grief components altogether as a separate, lightweight script.

I suggested the rename to 2.3 because of the changes to the Anti-Grief but we're discussing what you suggested to splitting the AG into a subscript, since it would be easier on everyone for future maintenance, and further justify the jump in versioning. It's up to Dread in the end, but I think that splitting the AG out into it's own script is the most ideal situation for an update, it makes it actually realistically option as opposed to having a toggle but the code chunk still being there, and the only time the two scripts need to communicate is when the AG is triggered, which means we're splitting up the math too.

**Pull request closed without merging**
